# Generated by Django 3.2.4 on 2021-07-20 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escritor',
            name='correo',
        ),
    ]
